version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/soloud"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/soloud-derive"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/soloud-sys"
    schedule:
      interval: "daily"
